### ISSUE TITLE
Conflicting configuration mechanisms

### ISSUE THREAD

**Issue by sspreitzer** [linux-system-roles/postfix#16]
https://github.com/linux-system-roles/postfix/blob/2a1b47b253b5305ec8ce50588950cec290ae3101/tasks/main.yml#L26

This role manages the configuration file via postconf, not Ansible. Ansible comments and statements are disambigious.

**Comment by spetrosi** [comment]
Indeed, the role does not manage the `/etc/postconf/main.cf` directly, but it does manage it with `postconf`. And yet, changes done to this file can be overwritten on the next role invocation.
#42 has been fixed recently, it adds a `ansible_manage` variable at the top of the file.
