### ISSUE TITLE
ansible-lint reports errors

### ISSUE THREAD

**Issue by vcrhonek** [linux-system-roles/postfix#9]
--> Executing Ansible Lint on postfix/tests/tests_default.yml...
    [ANSIBLE0010] Package installs should not use latest
    postfix/tests/roles/linux-system-roles.postfix/tasks/main.yml:2
    Task/Handler: Install Postfix
    
    [ANSIBLE0013] Use shell only when shell functionality is required
    postfix/tests/roles/linux-system-roles.postfix/tasks/main.yml:8
    Task/Handler: Backup configuration
    
    [ANSIBLE0012] Commands should not change things if nothing needs doing
    postfix/tests/roles/linux-system-roles.postfix/tasks/main.yml:28
    Task/Handler: Configure Postfix

**Comment by richm** [comment]
@nhosoi I never could get tox working for this role - so we may have to fix ansible-lint/ansible-test issues in this role by running `ansible-lint` and `ansible-test sanity` manually

**Comment by spetrosi** [comment]
Tox tests are running on the role properly now
